progress: to 393

* debug activeState Kmodo


* discrete data structure:
$debug: for debug
$ssl_available

# ====================================
$conf
$defaultConfigPath
	C:/Program Files/Darwin Streaming Server/streamingadminserver.conf
$perl_path: /usr/bin/perl
$streamingadminserver_path:  path of this server
    

* vital -- 189
this vital info is put into $config if not defined.

%vital = ("port", 1220,
	  "sslport", 1240,
	  "root", "C:/Program Files/Darwin Streaming Server/AdminHtml",
	  "plroot", "C:\\Program Files\\Darwin Streaming Server\\Playlists\\",
	  "server", "QTSS 5.5 Admin Server/1.0",
	  "index_docs", "index.html parse_xml.cgi index.htm index.cgi",
	  "addtype_html", "text/html",
      "addtype_htm", "text/html",
	  "addtype_txt", "text/plain",
	  "addtype_gif", "image/gif",
	  "addtype_jpg", "image/jpeg",
	  "addtype_jpeg", "image/jpeg",
	  "addtype_cgi", "internal/cgi",
	  "addtype_mov", "video/quicktime",
	  "addtype_js", "application/x-javascript",
	  "realm", "QTSS Admin Server",
	  "qtssIPAddress", "localhost",
	  "qtssPort", "554",
	  "qtssName", "C:/Program Files/Darwin Streaming Server/DarwinStreamingServer.exe",
	  "qtssAutoStart", "1",
      "logfile", "C:/Program Files/Darwin Streaming Server/Logs/streamingadminserver.log",
	  "log", "1",
	  "logclear", "0",
	  "logtime", "168",
	  "messagesfile", "messages",
	  "gbrowse", "0",
	  "ssl", "0",
	  "crtfile", "C:/Program Files/Darwin Streaming Server/streamingadminserver.pem",
	  "keyfile", "C:/Program Files/Darwin Streaming Server/streamingadminserver.pem",
	  #"keypasswordfile", "",
	  "qtssQTPasswd", "C:/Program Files/Darwin Streaming Server/qtpasswd.exe",
	  "qtssPlaylistBroadcaster", "c:\\Program Files\\Darwin Streaming Server\\PlaylistBroadcaster.exe",
	  "qtssMP3Broadcaster", "c:\\Program Files\\Darwin Streaming Server\\MP3Broadcaster.exe",
	  "helpurl", "http://helpqt.apple.com/dssWebAdminHelpR3/dssWebAdmin.help/DSSHelp.htm",
	  "qtssAdmin", "streamingadmin",
  	  "cacheMessageFiles", "0",
	  #"pidfile", "C:/Program Files/Darwin Streaming Server/streamingadminserver.pid"
	  );

* Message

Message is handled in 
           sub LoadMessageHashes

  $messagesfile{"en"}
  $messagesfile{"de"}
  $messagesfile{"fr"}
  $messagesfile{"jp"}
       D:\GitHub\DSS-Perl\AdminHtml\html_en\messages

  $messages{$lang}->{$keywore}=$messageStr;



* %ENV

%ENV
[
  "QTSSADMINSERVER_FR_MESSAGEHASH",
  {
    AccessHistFileReq                      => "File Requested",
    "AccessHistFilesReqHeader"             => "Files Requested Since Last Reset",
    AccessHistHeader                       => "Access History",
    AccessHistReqCount                     => "Requests",
    AprStr                                 => "Apr",
    AugStr                                 => "Aug",
    BitsPerSecStr                          => "bps",
    BytesStr                               => "Bytes",
    CancelButtonTitle                      => "Cancel",
    "ChBoradcastPassCannotBeAdminUser"     => "Your broadcast username cannot be the same as your administrator username.",
    "ChBroadcastPassAllowUnrestricted"     => "Allow unrestricted broadcasting",
    "ChBroadcastPassHeader"                => "Change Broadcast Username/Password",
    "ChBroadcastPassSpacesText"            => "Your broadcast username cannot contain spaces.",
    "ChMP3PassChangePasswdButton"          => "Change Broadcast Password",
    "ChMP3PassCurrentPasswd"               => "Current Password:",
    ChMP3PassErrorHeader                   => "Error",
    "ChMP3PassErrorNoQuotes"               => "Your MP3 password cannot contain quotation marks.",
    "ChMP3PassErrorNoSpaces"               => "Your MP3 password cannot contain spaces.",
    ChMP3PassErrorText                     => "An error occurred while changing your password.",
    ChMP3PassHeader                        => "Change MP3 Broadcast Password",
    ChMP3PassNewPasswd                     => "New Password:",
    "ChMP3PassNoAmpersands"                => "Your MP3 password cannot contain ampersands.",
    ChMP3PassNoBrackets                    => "Your MP3 password cannot contain < or > symbols.",
    "ChMP3PassNoHighBitStr"                => "Your MP3 password cannot have high-bit characters.",
    "ChMP3PassNoMatchHeader"               => "Passwords don't match",
    ChMP3PassNoMatchText                   => "The two passwords you entered don't match. Please try again.",
    "ChMP3PassNoPercentageMarks"           => "Your MP3 password cannot contain % symbols.",
    "ChMP3PassOldPasswdWrongHeader"        => "Incorrect Password",
    "ChMP3PassOldPasswdWrongText"          => "The old password was entered incorrectly. Please try again.",
    "ChMP3PassReenterPasswd"               => "Re-enter New Password:",
    ChMP3PassSavedText                     => "Your new broadcast password has been saved.",
    "ChPassCannotContainSpacesText"        => "Your administrator name cannot contain spaces.",
    "ChPassCannotHaveQuotesHeader"         => "Username/Password has a quote character",
    "ChPassCannotHaveQuotesText"           => "Your username/password cannot quote characters (either single or double).",
    "ChPassChangePasswdButton"             => "Change Password",
    ChPassCurrentPasswd                    => "Current Password:",
    ChPassCurrentUser                      => "Current User Name:",
    ChPassErrorHeader                      => "Error",
    ChPassErrorText                        => "An error occurred while changing your password.",
    ChPassHeader                           => "Change Administrator Username/Password",
    "ChPassMustEnterPasswdString"          => "You must enter a password.",
    ChPassNewPasswd                        => "New Password:",
    ChPassNewUser                          => "New User Name:",
    ChPassNoHighBitStr                     => "Your username/password cannot have high-bit characters.",
    ChPassNoMatchHeader                    => "Passwords don't match",
    ChPassNoMatchText                      => "The two passwords you entered don't match. Please try again.",
    "ChPassNotLongerThan80Header"          => "Password too long",
    "ChPassNotLongerThan80Text"            => "Your password cannot be longer than 80 characters.",
    "ChPassOldPasswdWrongHeader"           => "Incorrect Password",
    "ChPassOldPasswdWrongText"             => "The old password was entered incorrectly. Please try again.",
    ChPassReenterPasswd                    => "Re-enter New Password:",
    ChPassSavedText                        => "Your new password has been saved.",
    "ChPassUsernameCannotHaveColonHeader"  => "Username has : character",
    "ChPassUsernameCannotHaveColonText"    => "Your username cannot have the colon (:) character.",
    "ChPassUsernameNotLongerThan255Header" => "Username longer than 255 characters",
    "ChPassUsernameNotLongerThan255Text"   => "Your username cannot be longer than 255 characters.",
    ConfirmColor                           => "#006600",
    ConfirmSecs                            => 5,
    ConnUserAllEntries                     => "all",
    ConnUserBitRate                        => "Bit Rate",
    ConnUserBytesSent                      => "Bytes Sent",
    ConnUserConnType                       => "Type",
    ConnUserConnectedTo                    => "Connected To",
    ConnUserDisplay                        => "Display",
    ConnUserEntries                        => "entries",
    ConnUserHeader                         => "Connected Users",
    ConnUserHour                           => "hour",
    ConnUserIPAddress                      => "IP Address",
    ConnUserMinute                         => "minute",
    ConnUserMinutes                        => "minutes",
    ConnUserNever                          => "Never",
    "ConnUserPageRefreshInterval"          => "Page Refresh Interval",
    "ConnUserPercPacketLoss"               => "% Packet Loss",
    ConnUserSeconds                        => "seconds",
    "ConnUserTimeConnected"                => "Time Connected",
    ConnectFailedError                     => "Connect Failed",
    DaySuffix                              => "",
    DaysStr                                => "days",
    DecStr                                 => "Dec",
    Disabled                               => "Disabled",
    Enabled                                => "Enabled",
    ErrorLogHeader                         => "Error Log",
    ErrorLogReset                          => "Reset Error Log",
    ErrorLogResetConf                      => "The error log has been reset successfully.",
    FebStr                                 => "Feb",
    FileOpenError                          => "Can't open file",
    FriStr                                 => "Fri",
    GenSetBasicAuth                        => "Basic",
    "GenSetChangeAdminPass"                => "Change Admin Username/Password...",
    "GenSetChangeBroadcastPass"            => "Change Movie Broadcast Password...",
    GenSetChangeMP3Pass                    => "Change MP3 Broadcast Password...",
    "GenSetDefaultAuthScheme"              => "Default Authentication Scheme:",
    GenSetDigestAuth                       => "Digest",
    "GenSetErrorMaxConnCannotBeBlank"      => "The maximum connections setting cannot be blank.",
    "GenSetErrorMaxConnMustBeNum"          => "The maximum connections setting must be a positive integer.",
    "GenSetErrorMaxThroughCannotBeBlank"   => "The maximum throughput setting cannot be blank.",
    "GenSetErrorMaxThroughMustBeNum"       => "The maximum throughput setting must be a positive integer.",
    "GenSetErrorMediaDirCannotBeBlank"     => "The media directory cannot be blank.",
    "GenSetErrorSSLNotAvail"               => "SSL is not available on this computer. Please make sure that the Net::SSLeay perl module, OpenSSL, and a signed SSL certificate are installed.",
    GenSetHeader                           => "General Settings",
    GenSetMaxConn                          => "Max. Number of Connections:",
    GenSetMaxThroughput                    => "Max. Throughput:",
    GenSetMediaDir                         => "Media Directory:",
    GenSetMediaDirExp                      => "This is the master directory where all of your media is stored.",
    GenSetOSXAutoStart                     => "Start Server at System Startup:",
    GenSetSSL                              => "Secure Administration (SSL):",
    "GenSetSettingsSavedText"              => "Your settings have been saved.",
    GigaBytesStr                           => "GB",
    HoursStr                               => "hrs",
    Http200Status                          => "OK",
    Http302Status                          => "Temporarily Unavailable",
    Http401Body                            => "A password is required to administer this Streaming Server. Please Try Again.",
    Http401Status                          => "Unauthorized",
    Http403Body                            => "Access to the requested file is denied.",
    Http403Status                          => "Forbidden",
    Http404Body                            => "The requested file was not found.",
    Http404Status                          => "File Not Found",
    JanStr                                 => "Jan",
    JulStr                                 => "Jul",
    JunStr                                 => "Jun",
    KiloBytesStr                           => "KB",
    KilobitsPerSecStr                      => "Kbps",
    LogSetAccessLog                        => "Access Log",
    LogSetAccessLogging                    => "Logging:",
    LogSetDays                             => "days",
    LogSetErrorLogHeader                   => "Error Log",
    LogSetErrorLogging                     => "Logging:",
    "LogSetErrorValidationError"           => "All of the settings on this screen must be positive integers.",
    LogSetEvery                            => "every",
    LogSetHeader                           => "Log Settings",
    LogSetRollAccessLog                    => "Roll log:",
    LogSetRollErrorLog                     => "Roll log:",
    LogSetSavedHeader                      => "Log Settings Saved",
    LogSetSavedText                        => "Your settings have been saved.",
    LoginButton                            => "Log In",
    LoginPassword                          => "Password:",
    LoginPleaseLogin                       => "Log in with an administrative username and password.",
    LoginTitle                             => "Log In to Darwin Streaming Server",
    LoginUsername                          => "User Name:",
    MarStr                                 => "Mar",
    MayStr                                 => "May",
    MegaBytesStr                           => "MB",
    MegabitsPerSecStr                      => "Mbps",
    MinutesStr                             => "min",
    MonStr                                 => "Mon",
    MountPoint                             => "Mount Point:",
    NavAccessHistory                       => "Access History",
    NavBroadcaster                         => "Broadcaster",
    NavConnectedUsers                      => "Connected Users",
    NavErrorLog                            => "Error Log",
    NavGeneralSettings                     => "General Settings",
    NavLogOut                              => "Log Out",
    NavLogSettings                         => "Log Settings",
    NavMain                                => "Main",
    NavPlaylists                           => "Playlists",
    NavPortSettings                        => "Port Settings",
    NavRelaySettings                       => "Relay Settings",
    NavRelayStatus                         => "Relay Status",
    NoHostError                            => "No Host",
    NovStr                                 => "Nov",
    OKButtonTitle                          => "OK",
    OctStr                                 => "Oct",
    PLAvailableMedia                       => "Available Content:",
    PLAvailablePlaylists                   => "Available Playlists:",
    PLChangedHeader                        => "Playlist Status(es) Changed",
    PLChangedText                          => "The status of your playlist has been changed.",
    PLCreateErrorHeader                    => "Error",
    PLCreateErrorText                      => "An error occurred while creating your playlist.",
    PLCreatedText                          => "Your playlist was saved successfully.",
    PLDefaultGenre                         => "Pop",
    "PLDefaultMP3PlaylistMountPoint"       => "/untitled",
    "PLDefaultMoviePlaylistSDP"            => "untitled.sdp",
    "PLDefaultPlaylistName"                => "untitled",
    PLDeleteButton                         => "Delete Playlist",
    PLDeleteConfirm                        => "Are you sure you want to delete the selected playlist?",
    PLDeleteErrorHeader                    => "Error",
    PLDeleteErrorText                      => "An error occurred while deleting your playlist.",
    PLDeleteText                           => "Your playlist was deleted successfully.",
    PLDirectory                            => "Directory",
    PLEditButton                           => "Edit Playlist",
    "PLErrMountPointCannotBeBlank"         => "The mount point cannot be blank.",
    "PLErrMountPointCannotContainSpaces"   => "The mount point cannot contain spaces.",
    "PLErrNameCannotBeBlank"               => "The playlist name cannot be blank.",
    PLErrNameConflict                      => "A playlist with this name already exists. Please choose a different name.",
    "PLErrRepetitionTooLarge"              => "The repetition value for weighted random playlists cannot be higher than the number of songs in the playlist.",
    PLErrorHeader                          => "Error",
    PLErrorLogHeader                       => "Playlist Error Log",
    PLErrorText                            => "An error occurred while starting or stopping your playlist.",
    PLGenre                                => "Genre:",
    PLHeader                               => "Playlists",
    PLInstructions                         => "Click and drag files from the left to the right to add to your playlist.",
    PLItemsHavePlayed                      => "other items have played",
    PLItemsInPlaylist                      => "Items in This Playlist:",
    PLItemsRepeatAfter                     => "Items only repeat after",
    PLLogging                              => "Log this playlist's activity",
    PLMP3PlaylistDetails                   => "MP3 Playlist Details",
    PLMovie                                => "Movie",
    "PLMoviePlaylistDetails"               => "Media Playlist Details",
    PLName                                 => "Name:",
    PLNewMP3                               => "New MP3 Playlist",
    PLNewMovie                             => "New Media Playlist",
    PLOpenFolderButton                     => "Open Folder",
    PLOrderHeader                          => "Order",
    PLPlayMode                             => "Play Mode:",
    PLPlayModeSequential                   => "Sequential",
    "PLPlayModeSequentialLooped"           => "Sequential Looped",
    "PLPlayModeWeightedRandom"             => "Weighted Random",
    PLRelayToExternal                      => "Send this playlist to a broadcast server",
    PLRemoveItemButton                     => "Remove Item",
    "PLReorderInstructions"                => "Drag items in your playlist up or down to reorder them.",
    PLRepetition                           => "Repetition:",
    "PLSetBroadcastPasswordConfirm"        => "You must set an MP3 Broadcast Password before starting a playlist. Set a password now?",
    "PLStartBeforeTestingConfirm"          => "This playlist must be started before viewing its publishing info. Start the playlist now?",
    PLStarted                              => "Playing",
    PLState_0                              => "stopped",
    PLState_1                              => "playing",
    PLState_2                              => "error",
    PLStopped                              => "Stopped",
    PLTitleHeader                          => "Title",
    PLWeightHeader                         => "Weight",
    Password                               => "Password:",
    "PortChangeRestartServerConfirm"       => "In order for this change to take effect, you must restart the server. This will interrupt any current streams. Restart now?",
    "PortServerNotBound80Message"          => "The server is currently not bound to port 80.",
    PortSetDesc1                           => "Streaming on port 80 will allow you to get through some restrictive firewalls, but may interfere with Apache or other web servers running on the same machine.",
    PortSetDesc2                           => "",
    PortSetHeader                          => "Port Settings",
    PortSetSavedText                       => "Your port settings have been saved.",
    "PortSetStreaming80Title"              => "Streaming on Port 80:",
    QTBAudioPreset                         => "Audio",
    QTBBufferDelay                         => "Buffer Delay",
    QTBConfQuit                            => "The broadcaster application is no longer running.",
    QTBConfSaved                           => "Your broadcaster settings have been saved.",
    QTBConfStarted                         => "The broadcast has been started.",
    QTBConfStopped                         => "The broadcast has been stopped.",
    QTBCurrentStatus                       => "Current Status",
    "QTBErrAlreadyRunningText"             => "The broadcaster cannot be remotely administered after it's launched from the Finder. Restart the broadcaster now?",
    "QTBErrAlreadyRunningTitle"            => "Restart Broadcaster?",
    "QTBErrBroadcastSettings"              => "The brodcast could not be started, because an error occurred.",
    "QTBErrNotInstalledText"               => "QuickTime Broadcaster is not installed in the /Applications folder.",
    QTBErrNotRunningText                   => "The broadcaster is not currently running. Start it now?",
    "QTBErrNotRunningTitle"                => "Start broadcaster?",
    "QTBQuitBroadcasterButton"             => "Quit Broadcaster",
    QTBSDPFile                             => "SDP File",
    QTBStartButton                         => "Start Broadcast",
    QTBStateBroadcasting                   => "Broadcasting",
    QTBStatePrerolling                     => "Prerolling",
    QTBStateSetup                          => "Setup",
    "QTBStateStartingBroadcast"            => "Starting Broadcast",
    "QTBStateStoppingBroadcast"            => "Stopping Broadcast",
    QTBStopButton                          => "Stop Broadcast",
    QTBTitle                               => "Broadcaster Settings",
    QTBVideoPreset                         => "Video",
    QTBViewBroadcast                       => "View Broadcast",
    QTLoginTitle                           => "Log In to QuickTime Streaming Server",
    QTServerName                           => "QuickTime Streaming Server",
    "RelayDefaultRelayHeader"              => "Default Relay:",
    "RelayDefaultRelayName"                => "Default Relay",
    RelayDeleteConfirm                     => "Are you sure you want to delete the selected relay?",
    "RelayDeleteSourceButton"              => "Delete Relay",
    RelayDeleteText                        => "Your relay was deleted successfully.",
    "RelayDetailsAddDestination"           => "Add Destination",
    "RelayDetailsDeleteDestination"        => "Remove Destination",
    "RelayDetailsDestAnnounced"            => "Announced UDP",
    "RelayDetailsDestBasePort"             => "Base Port:",
    "RelayDetailsDestHostname"             => "Hostname or IP Address:",
    "RelayDetailsDestMulticastTTL"         => "Multicast TTL:",
    RelayDetailsDestUDP                    => "Unannounced UDP",
    "RelayDetailsDestinationHeader"        => "Destination Settings",
    RelayDetailsHeader                     => "Relay Details",
    "RelayDetailsRelayName"                => "Relay Name:",
    "RelayDetailsSourceHostname"           => "Source Hostname or IP Address:",
    "RelayDetailsSourceRequestStream"      => "Request incoming stream",
    "RelayDetailsSourceSettingsHeader"     => "Source Settings",
    "RelayDetailsSourceWait"               => "Wait for announced stream(s)",
    RelayDetailsStatus                     => "Status:",
    "RelayEditDefaultSourceButton"         => "Edit Default Relay",
    "RelayEditSourceButton"                => "Edit Relay",
    "RelayErrMulticastTTLIncorrect"        => "The Multicast TTL must be a number between 1 and 255.",
    RelayErrNoName                         => "You must enter a relay name.",
    RelayErrNoSourceIP                     => "You must enter a source IP address or hostname.",
    RelayNameHeader                        => "Name",
    RelayNewSourceButton                   => "New Relay",
    RelaySaveText                          => "Your relay was saved successfully.",
    RelaySources                           => "Other Relays:",
    RelayStatBitrate                       => "Bit Rate",
    "RelayStatBytesRelayed"                => "Bytes Relayed",
    RelayStatConnRelays                    => "Connected Relays",
    RelayStatDestination                   => "Destination",
    RelayStatHeader                        => "Relay Status",
    RelayStatRelayName                     => "Relay Name",
    RelayStatSource                        => "Source",
    RelayStatusDisabled                    => "Disabled",
    RelayStatusEnabled                     => "Enabled",
    RelayStatusHeader                      => "Status",
    SatStr                                 => "Sat",
    SecondsStr                             => "sec",
    SendFailedError                        => "Send failed",
    SepStr                                 => "Sep",
    ServerIdleStr                          => "Idle",
    "ServerInFatalErrorStateStr"           => "In Fatal Error State",
    ServerName                             => "Darwin Streaming Server",
    "ServerNotRunningMessage"              => "Streaming Server is not Running",
    ServerNotRunningStr                    => "Not Running",
    "ServerRefusingConnectionsStr"         => "Refusing Connections",
    ServerRunningStr                       => "Running",
    ServerServerIs                         => "Server is",
    "ServerShuttingDownStr"                => "Shutting Down",
    ServerStartingUpStr                    => "Starting Up",
    ServerStartupExpText                   => "The server is currently not running.<br>Please start it before attempting to administer it.",
    SetupAssist80Exp                       => "This allows you to stream through firewalls.",
    SetupAssist80Label                     => "Streaming on Port 80",
    "SetupAssistFinishButton"              => "Finish",
    SetupAssistFolderExp                   => "This is the folder or directory in which your media is stored.",
    "SetupAssistMP3PassExp"                => "The MP3 Broadcast password is required in order to receive MP3 broadcast streams.",
    "SetupAssistMediaFolder"               => "Media Folder:",
    "SetupAssistNextButton"                => "Next",
    "SetupAssistNoUsername"                => "You must enter a valid username and password.",
    "SetupAssistNoUsernameHeader"          => "Invalid Username/Password",
    SetupAssistPassExp                     => "This is the password used to administer the server.",
    "SetupAssistPrevButton"                => "Prev",
    SetupAssistSSLExp                      => "This will enable encryption between the administration server and the web client.  This feature requires that you have a valid streaming server SSL certificate installed.",
    SetupAssistSSLLabel                    => "Secure Administration (SSL)",
    "SetupAssistSetPasswordButton"         => "Set Password",
    "SetupAssistSkipButton"                => "Cancel",
    SetupAssistStep1                       => "Assign Username/Password",
    SetupAssistStep2                       => "MP3 Broadcast Password",
    SetupAssistStep3                       => "Secure Administration",
    SetupAssistStep4                       => "Media Folder",
    SetupAssistStep5                       => "Streaming on Port 80",
    SetupAssistTitle                       => "Setup Assistant",
    SnapshotCPULoad                        => "CPU Load:",
    "SnapshotCurrentConnectionCount"       => "Current # of Connections:",
    "SnapshotCurrentThroughput"            => "Current Throughput:",
    "SnapshotCurrentTimeOnServer"          => "Current Time On Server:",
    SnapshotDNSName                        => "DNS Name (default):",
    SnapshotHeader                         => "Server Snapshot",
    SnapshotServer                         => "Server:",
    "SnapshotServerAPIVersion"             => "Server API Version:",
    "SnapshotServerVersion"                => "Server Version:",
    SnapshotStarted                        => "Started",
    SnapshotStatus                         => "Status:",
    "SnapshotTotalBytesServed"             => "Total Bytes Served:",
    "SnapshotTotalConnectionsServed"       => "Total Connections Served:",
    SnapshotUptime                         => "Up Time:",
    SocketFailedError                      => "Socket Failed",
    StartServerButton                      => "Enable Server",
    StartServerMessage                     => "Click on 'Start Server Now' to start the server.",
    StopServerButton                       => "Disable Server",
    SubmitButtonTitle                      => "Save Changes",
    SunStr                                 => "Sun",
    ThuStr                                 => "Thu",
    TueStr                                 => "Tue",
    Username                               => "User Name:",
    WedStr                                 => "Wed",
    YearSuffix                             => "",
    announced_source                       => "Pull",
    of                                     => "of",
    rtsp_source                            => "Push",
  },
  "DBGP_COOKIE",
  "tp2D9uaPQieXxelRUvp50g==",
  "USER_AGENT",
  "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36",
  "SCRIPT_NAME",
  "/",
  "CLASSPATH_ALGORITHMS",
  "D:\\z_books\\dataStructure\\Algorithms_4e_RobertSedgewick\\bin",
  "HTTP_ACCEPT",
  "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
  "REQUEST_METHOD",
  "GET",
  "QTSSADMINSERVER_EN_MESSAGEHASH",
  {
    AccessHistFileReq                      => "File Requested",
    "AccessHistFilesReqHeader"             => "Files Requested Since Last Reset",
    AccessHistHeader                       => "Access History",
    AccessHistReqCount                     => "Requests",
    AprStr                                 => "Apr",
    AugStr                                 => "Aug",
    BitsPerSecStr                          => "bps",
    BytesStr                               => "Bytes",
    CancelButtonTitle                      => "Cancel",
    "ChBoradcastPassCannotBeAdminUser"     => "Your broadcast username cannot be the same as your administrator username.",
    "ChBroadcastPassAllowUnrestricted"     => "Allow unrestricted broadcasting",
    "ChBroadcastPassHeader"                => "Change Broadcast Username/Password",
    "ChBroadcastPassSpacesText"            => "Your broadcast username cannot contain spaces.",
    "ChMP3PassChangePasswdButton"          => "Change Broadcast Password",
    "ChMP3PassCurrentPasswd"               => "Current Password:",
    ChMP3PassErrorHeader                   => "Error",
    "ChMP3PassErrorNoQuotes"               => "Your MP3 password cannot contain quotation marks.",
    "ChMP3PassErrorNoSpaces"               => "Your MP3 password cannot contain spaces.",
    ChMP3PassErrorText                     => "An error occurred while changing your password.",
    ChMP3PassHeader                        => "Change MP3 Broadcast Password",
    ChMP3PassNewPasswd                     => "New Password:",
    "ChMP3PassNoAmpersands"                => "Your MP3 password cannot contain ampersands.",
    ChMP3PassNoBrackets                    => "Your MP3 password cannot contain < or > symbols.",
    "ChMP3PassNoHighBitStr"                => "Your MP3 password cannot have high-bit characters.",
    "ChMP3PassNoMatchHeader"               => "Passwords don't match",
    ChMP3PassNoMatchText                   => "The two passwords you entered don't match. Please try again.",
    "ChMP3PassNoPercentageMarks"           => "Your MP3 password cannot contain % symbols.",
    "ChMP3PassOldPasswdWrongHeader"        => "Incorrect Password",
    "ChMP3PassOldPasswdWrongText"          => "The old password was entered incorrectly. Please try again.",
    "ChMP3PassReenterPasswd"               => "Re-enter New Password:",
    ChMP3PassSavedText                     => "Your new broadcast password has been saved.",
    "ChPassCannotContainSpacesText"        => "Your administrator name cannot contain spaces.",
    "ChPassCannotHaveQuotesHeader"         => "Username/Password has a quote character",
    "ChPassCannotHaveQuotesText"           => "Your username/password cannot quote characters (either single or double).",
    "ChPassChangePasswdButton"             => "Change Password",
    ChPassCurrentPasswd                    => "Current Password:",
    ChPassCurrentUser                      => "Current User Name:",
    ChPassErrorHeader                      => "Error",
    ChPassErrorText                        => "An error occurred while changing your password.",
    ChPassHeader                           => "Change Administrator Username/Password",
    "ChPassMustEnterPasswdString"          => "You must enter a password.",
    ChPassNewPasswd                        => "New Password:",
    ChPassNewUser                          => "New User Name:",
    ChPassNoHighBitStr                     => "Your username/password cannot have high-bit characters.",
    ChPassNoMatchHeader                    => "Passwords don't match",
    ChPassNoMatchText                      => "The two passwords you entered don't match. Please try again.",
    "ChPassNotLongerThan80Header"          => "Password too long",
    "ChPassNotLongerThan80Text"            => "Your password cannot be longer than 80 characters.",
    "ChPassOldPasswdWrongHeader"           => "Incorrect Password",
    "ChPassOldPasswdWrongText"             => "The old password was entered incorrectly. Please try again.",
    ChPassReenterPasswd                    => "Re-enter New Password:",
    ChPassSavedText                        => "Your new password has been saved.",
    "ChPassUsernameCannotHaveColonHeader"  => "Username has : character",
    "ChPassUsernameCannotHaveColonText"    => "Your username cannot have the colon (:) character.",
    "ChPassUsernameNotLongerThan255Header" => "Username longer than 255 characters",
    "ChPassUsernameNotLongerThan255Text"   => "Your username cannot be longer than 255 characters.",
    ConfirmColor                           => "#006600",
    ConfirmSecs                            => 5,
    ConnUserAllEntries                     => "all",
    ConnUserBitRate                        => "Bit Rate",
    ConnUserBytesSent                      => "Bytes Sent",
    ConnUserConnType                       => "Type",
    ConnUserConnectedTo                    => "Connected To",
    ConnUserDisplay                        => "Display",
    ConnUserEntries                        => "entries",
    ConnUserHeader                         => "Connected Users",
    ConnUserHour                           => "hour",
    ConnUserIPAddress                      => "IP Address",
    ConnUserMinute                         => "minute",
    ConnUserMinutes                        => "minutes",
    ConnUserNever                          => "Never",
    "ConnUserPageRefreshInterval"          => "Page Refresh Interval",
    "ConnUserPercPacketLoss"               => "% Packet Loss",
    ConnUserSeconds                        => "seconds",
    "ConnUserTimeConnected"                => "Time Connected",
    ConnectFailedError                     => "Connect Failed",
    DaySuffix                              => "",
    DaysStr                                => "days",
    DecStr                                 => "Dec",
    Disabled                               => "Disabled",
    Enabled                                => "Enabled",
    ErrorLogHeader                         => "Error Log",
    ErrorLogReset                          => "Reset Error Log",
    ErrorLogResetConf                      => "The error log has been reset successfully.",
    FebStr                                 => "Feb",
    FileOpenError                          => "Can't open file",
    FriStr                                 => "Fri",
    GenSetBasicAuth                        => "Basic",
    "GenSetChangeAdminPass"                => "Change Admin Username/Password...",
    "GenSetChangeBroadcastPass"            => "Change Movie Broadcast Password...",
    GenSetChangeMP3Pass                    => "Change MP3 Broadcast Password...",
    "GenSetDefaultAuthScheme"              => "Default Authentication Scheme:",
    GenSetDigestAuth                       => "Digest",
    "GenSetErrorMaxConnCannotBeBlank"      => "The maximum connections setting cannot be blank.",
    "GenSetErrorMaxConnMustBeNum"          => "The maximum connections setting must be a positive integer.",
    "GenSetErrorMaxThroughCannotBeBlank"   => "The maximum throughput setting cannot be blank.",
    "GenSetErrorMaxThroughMustBeNum"       => "The maximum throughput setting must be a positive integer.",
    "GenSetErrorMediaDirCannotBeBlank"     => "The media directory cannot be blank.",
    "GenSetErrorSSLNotAvail"               => "SSL is not available on this computer. Please make sure that the Net::SSLeay perl module, OpenSSL, and a signed SSL certificate are installed.",
    GenSetHeader                           => "General Settings",
    GenSetMaxConn                          => "Max. Number of Connections:",
    GenSetMaxThroughput                    => "Max. Throughput:",
    GenSetMediaDir                         => "Media Directory:",
    GenSetMediaDirExp                      => "This is the master directory where all of your media is stored.",
    GenSetOSXAutoStart                     => "Start Server at System Startup:",
    GenSetSSL                              => "Secure Administration (SSL):",
    "GenSetSettingsSavedText"              => "Your settings have been saved.",
    GigaBytesStr                           => "GB",
    HoursStr                               => "hrs",
    Http200Status                          => "OK",
    Http302Status                          => "Temporarily Unavailable",
    Http401Body                            => "A password is required to administer this Streaming Server. Please Try Again.",
    Http401Status                          => "Unauthorized",
    Http403Body                            => "Access to the requested file is denied.",
    Http403Status                          => "Forbidden",
    Http404Body                            => "The requested file was not found.",
    Http404Status                          => "File Not Found",
    JanStr                                 => "Jan",
    JulStr                                 => "Jul",
    JunStr                                 => "Jun",
    KiloBytesStr                           => "KB",
    KilobitsPerSecStr                      => "Kbps",
    LogSetAccessLog                        => "Access Log",
    LogSetAccessLogging                    => "Logging:",
    LogSetDays                             => "days",
    LogSetErrorLogHeader                   => "Error Log",
    LogSetErrorLogging                     => "Logging:",
    "LogSetErrorValidationError"           => "All of the settings on this screen must be positive integers.",
    LogSetEvery                            => "every",
    LogSetHeader                           => "Log Settings",
    LogSetRollAccessLog                    => "Roll log:",
    LogSetRollErrorLog                     => "Roll log:",
    LogSetSavedHeader                      => "Log Settings Saved",
    LogSetSavedText                        => "Your settings have been saved.",
    LoginButton                            => "Log In",
    LoginPassword                          => "Password:",
    LoginPleaseLogin                       => "Log in with an administrative username and password.",
    LoginTitle                             => "Log In to Darwin Streaming Server",
    LoginUsername                          => "User Name:",
    MarStr                                 => "Mar",
    MayStr                                 => "May",
    MegaBytesStr                           => "MB",
    MegabitsPerSecStr                      => "Mbps",
    MinutesStr                             => "min",
    MonStr                                 => "Mon",
    MountPoint                             => "Mount Point:",
    NavAccessHistory                       => "Access History",
    NavBroadcaster                         => "Broadcaster",
    NavConnectedUsers                      => "Connected Users",
    NavErrorLog                            => "Error Log",
    NavGeneralSettings                     => "General Settings",
    NavLogOut                              => "Log Out",
    NavLogSettings                         => "Log Settings",
    NavMain                                => "Main",
    NavPlaylists                           => "Playlists",
    NavPortSettings                        => "Port Settings",
    NavRelaySettings                       => "Relay Settings",
    NavRelayStatus                         => "Relay Status",
    NoHostError                            => "No Host",
    NovStr                                 => "Nov",
    OKButtonTitle                          => "OK",
    OctStr                                 => "Oct",
    PLAvailableMedia                       => "Available Content:",
    PLAvailablePlaylists                   => "Available Playlists:",
    PLChangedHeader                        => "Playlist Status(es) Changed",
    PLChangedText                          => "The status of your playlist has been changed.",
    PLCreateErrorHeader                    => "Error",
    PLCreateErrorText                      => "An error occurred while creating your playlist.",
    PLCreatedText                          => "Your playlist was saved successfully.",
    PLDefaultGenre                         => "Pop",
    "PLDefaultMP3PlaylistMountPoint"       => "/untitled",
    "PLDefaultMoviePlaylistSDP"            => "untitled.sdp",
    "PLDefaultPlaylistName"                => "untitled",
    PLDeleteButton                         => "Delete Playlist",
    PLDeleteConfirm                        => "Are you sure you want to delete the selected playlist?",
    PLDeleteErrorHeader                    => "Error",
    PLDeleteErrorText                      => "An error occurred while deleting your playlist.",
    PLDeleteText                           => "Your playlist was deleted successfully.",
    PLDirectory                            => "Directory",
    PLEditButton                           => "Edit Playlist",
    "PLErrMountPointCannotBeBlank"         => "The mount point cannot be blank.",
    "PLErrMountPointCannotContainSpaces"   => "The mount point cannot contain spaces.",
    "PLErrNameCannotBeBlank"               => "The playlist name cannot be blank.",
    PLErrNameConflict                      => "A playlist with this name already exists. Please choose a different name.",
    "PLErrRepetitionTooLarge"              => "The repetition value for weighted random playlists cannot be higher than the number of songs in the playlist.",
    PLErrorHeader                          => "Error",
    PLErrorLogHeader                       => "Playlist Error Log",
    PLErrorText                            => "An error occurred while starting or stopping your playlist.",
    PLGenre                                => "Genre:",
    PLHeader                               => "Playlists",
    PLInstructions                         => "Click and drag files from the left to the right to add to your playlist.",
    PLItemsHavePlayed                      => "other items have played",
    PLItemsInPlaylist                      => "Items in This Playlist:",
    PLItemsRepeatAfter                     => "Items only repeat after",
    PLLogging                              => "Log this playlist's activity",
    PLMP3PlaylistDetails                   => "MP3 Playlist Details",
    PLMovie                                => "Movie",
    "PLMoviePlaylistDetails"               => "Media Playlist Details",
    PLName                                 => "Name:",
    PLNewMP3                               => "New MP3 Playlist",
    PLNewMovie                             => "New Media Playlist",
    PLOpenFolderButton                     => "Open Folder",
    PLOrderHeader                          => "Order",
    PLPlayMode                             => "Play Mode:",
    PLPlayModeSequential                   => "Sequential",
    "PLPlayModeSequentialLooped"           => "Sequential Looped",
    "PLPlayModeWeightedRandom"             => "Weighted Random",
    PLRelayToExternal                      => "Send this playlist to a broadcast server",
    PLRemoveItemButton                     => "Remove Item",
    "PLReorderInstructions"                => "Drag items in your playlist up or down to reorder them.",
    PLRepetition                           => "Repetition:",
    "PLSetBroadcastPasswordConfirm"        => "You must set an MP3 Broadcast Password before starting a playlist. Set a password now?",
    "PLStartBeforeTestingConfirm"          => "This playlist must be started before viewing its publishing info. Start the playlist now?",
    PLStarted                              => "Playing",
    PLState_0                              => "stopped",
    PLState_1                              => "playing",
    PLState_2                              => "error",
    PLStopped                              => "Stopped",
    PLTitleHeader                          => "Title",
    PLWeightHeader                         => "Weight",
    Password                               => "Password:",
    "PortChangeRestartServerConfirm"       => "In order for this change to take effect, you must restart the server. This will interrupt any current streams. Restart now?",
    "PortServerNotBound80Message"          => "The server is currently not bound to port 80.",
    PortSetDesc1                           => "Streaming on port 80 will allow you to get through some restrictive firewalls, but may interfere with Apache or other web servers running on the same machine.",
    PortSetDesc2                           => "",
    PortSetHeader                          => "Port Settings",
    PortSetSavedText                       => "Your port settings have been saved.",
    "PortSetStreaming80Title"              => "Streaming on Port 80:",
    QTBAudioPreset                         => "Audio",
    QTBBufferDelay                         => "Buffer Delay",
    QTBConfQuit                            => "The broadcaster application is no longer running.",
    QTBConfSaved                           => "Your broadcaster settings have been saved.",
    QTBConfStarted                         => "The broadcast has been started.",
    QTBConfStopped                         => "The broadcast has been stopped.",
    QTBCurrentStatus                       => "Current Status",
    "QTBErrAlreadyRunningText"             => "The broadcaster cannot be remotely administered after it's launched from the Finder. Restart the broadcaster now?",
    "QTBErrAlreadyRunningTitle"            => "Restart Broadcaster?",
    "QTBErrBroadcastSettings"              => "The brodcast could not be started, because an error occurred.",
    "QTBErrNotInstalledText"               => "QuickTime Broadcaster is not installed in the /Applications folder.",
    QTBErrNotRunningText                   => "The broadcaster is not currently running. Start it now?",
    "QTBErrNotRunningTitle"                => "Start broadcaster?",
    "QTBQuitBroadcasterButton"             => "Quit Broadcaster",
    QTBSDPFile                             => "SDP File",
    QTBStartButton                         => "Start Broadcast",
    QTBStateBroadcasting                   => "Broadcasting",
    QTBStatePrerolling                     => "Prerolling",
    QTBStateSetup                          => "Setup",
    "QTBStateStartingBroadcast"            => "Starting Broadcast",
    "QTBStateStoppingBroadcast"            => "Stopping Broadcast",
    QTBStopButton                          => "Stop Broadcast",
    QTBTitle                               => "Broadcaster Settings",
    QTBVideoPreset                         => "Video",
    QTBViewBroadcast                       => "View Broadcast",
    QTLoginTitle                           => "Log In to QuickTime Streaming Server",
    QTServerName                           => "QuickTime Streaming Server",
    "RelayDefaultRelayHeader"              => "Default Relay:",
    "RelayDefaultRelayName"                => "Default Relay",
    RelayDeleteConfirm                     => "Are you sure you want to delete the selected relay?",
    "RelayDeleteSourceButton"              => "Delete Relay",
    RelayDeleteText                        => "Your relay was deleted successfully.",
    "RelayDetailsAddDestination"           => "Add Destination",
    "RelayDetailsDeleteDestination"        => "Remove Destination",
    "RelayDetailsDestAnnounced"            => "Announced UDP",
    "RelayDetailsDestBasePort"             => "Base Port:",
    "RelayDetailsDestHostname"             => "Hostname or IP Address:",
    "RelayDetailsDestMulticastTTL"         => "Multicast TTL:",
    RelayDetailsDestUDP                    => "Unannounced UDP",
    "RelayDetailsDestinationHeader"        => "Destination Settings",
    RelayDetailsHeader                     => "Relay Details",
    "RelayDetailsRelayName"                => "Relay Name:",
    "RelayDetailsSourceHostname"           => "Source Hostname or IP Address:",
    "RelayDetailsSourceRequestStream"      => "Request incoming stream",
    "RelayDetailsSourceSettingsHeader"     => "Source Settings",
    "RelayDetailsSourceWait"               => "Wait for announced stream(s)",
    RelayDetailsStatus                     => "Status:",
    "RelayEditDefaultSourceButton"         => "Edit Default Relay",
    "RelayEditSourceButton"                => "Edit Relay",
    "RelayErrMulticastTTLIncorrect"        => "The Multicast TTL must be a number between 1 and 255.",
    RelayErrNoName                         => "You must enter a relay name.",
    RelayErrNoSourceIP                     => "You must enter a source IP address or hostname.",
    RelayNameHeader                        => "Name",
    RelayNewSourceButton                   => "New Relay",
    RelaySaveText                          => "Your relay was saved successfully.",
    RelaySources                           => "Other Relays:",
    RelayStatBitrate                       => "Bit Rate",
    "RelayStatBytesRelayed"                => "Bytes Relayed",
    RelayStatConnRelays                    => "Connected Relays",
    RelayStatDestination                   => "Destination",
    RelayStatHeader                        => "Relay Status",
    RelayStatRelayName                     => "Relay Name",
    RelayStatSource                        => "Source",
    RelayStatusDisabled                    => "Disabled",
    RelayStatusEnabled                     => "Enabled",
    RelayStatusHeader                      => "Status",
    SatStr                                 => "Sat",
    SecondsStr                             => "sec",
    SendFailedError                        => "Send failed",
    SepStr                                 => "Sep",
    ServerIdleStr                          => "Idle",
    "ServerInFatalErrorStateStr"           => "In Fatal Error State",
    ServerName                             => "Darwin Streaming Server",
    "ServerNotRunningMessage"              => "Streaming Server is not Running",
    ServerNotRunningStr                    => "Not Running",
    "ServerRefusingConnectionsStr"         => "Refusing Connections",
    ServerRunningStr                       => "Running",
    ServerServerIs                         => "Server is",
    "ServerShuttingDownStr"                => "Shutting Down",
    ServerStartingUpStr                    => "Starting Up",
    ServerStartupExpText                   => "The server is currently not running.<br>Please start it before attempting to administer it.",
    SetupAssist80Exp                       => "This allows you to stream through firewalls.",
    SetupAssist80Label                     => "Streaming on Port 80",
    "SetupAssistFinishButton"              => "Finish",
    SetupAssistFolderExp                   => "This is the folder or directory in which your media is stored.",
    "SetupAssistMP3PassExp"                => "The MP3 Broadcast password is required in order to receive MP3 broadcast streams.",
    "SetupAssistMediaFolder"               => "Media Folder:",
    "SetupAssistNextButton"                => "Next",
    "SetupAssistNoUsername"                => "You must enter a valid username and password.",
    "SetupAssistNoUsernameHeader"          => "Invalid Username/Password",
    SetupAssistPassExp                     => "This is the password used to administer the server.",
    "SetupAssistPrevButton"                => "Prev",
    SetupAssistSSLExp                      => "This will enable encryption between the administration server and the web client.  This feature requires that you have a valid streaming server SSL certificate installed.",
    SetupAssistSSLLabel                    => "Secure Administration (SSL)",
    "SetupAssistSetPasswordButton"         => "Set Password",
    "SetupAssistSkipButton"                => "Cancel",
    SetupAssistStep1                       => "Assign Username/Password",
    SetupAssistStep2                       => "MP3 Broadcast Password",
    SetupAssistStep3                       => "Secure Administration",
    SetupAssistStep4                       => "Media Folder",
    SetupAssistStep5                       => "Streaming on Port 80",
    SetupAssistTitle                       => "Setup Assistant",
    SnapshotCPULoad                        => "CPU Load:",
    "SnapshotCurrentConnectionCount"       => "Current # of Connections:",
    "SnapshotCurrentThroughput"            => "Current Throughput:",
    "SnapshotCurrentTimeOnServer"          => "Current Time On Server:",
    SnapshotDNSName                        => "DNS Name (default):",
    SnapshotHeader                         => "Server Snapshot",
    SnapshotServer                         => "Server:",
    "SnapshotServerAPIVersion"             => "Server API Version:",
    "SnapshotServerVersion"                => "Server Version:",
    SnapshotStarted                        => "Started",
    SnapshotStatus                         => "Status:",
    "SnapshotTotalBytesServed"             => "Total Bytes Served:",
    "SnapshotTotalConnectionsServed"       => "Total Connections Served:",
    SnapshotUptime                         => "Up Time:",
    SocketFailedError                      => "Socket Failed",
    StartServerButton                      => "Enable Server",
    StartServerMessage                     => "Click on 'Start Server Now' to start the server.",
    StopServerButton                       => "Disable Server",
    SubmitButtonTitle                      => "Save Changes",
    SunStr                                 => "Sun",
    ThuStr                                 => "Thu",
    TueStr                                 => "Tue",
    Username                               => "User Name:",
    WedStr                                 => "Wed",
    YearSuffix                             => "",
    announced_source                       => "Pull",
    of                                     => "of",
    rtsp_source                            => "Push",
  },
  "VBOX_MSI_INSTALL_PATH",
  "C:\\Program Files\\Oracle\\VirtualBox\\",
  "PROGRAMFILES",
  "C:\\Program Files (x86)",
  "PWD",
  "C:/Program Files/Darwin Streaming Server/AdminHtml/",
  "LOCALAPPDATA",
  "C:\\Users\\andy\\AppData\\Local",
  "HTTP_USER_AGENT",
  "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36",
  "PROGRAMW6432",
  "C:\\Program Files",
  "COOKIE_EXPIRE_SECONDS",
  undef,
]
